import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import Database from "better-sqlite3";
import { afterEach, describe, expect, it, vi } from "vitest";
import { decodeAndValidateChallenge, decodePaymentResponse, executeX402scanOnceForTest, OneShotState, PinnedEip3009Signer, readIntentReadonly, reconcileIntent, runX402scanReconciliation, validateReceipt, X402SCAN_ROUTE, X402SCAN_WALLET, type LiveChallenge, type OneShotDependencies, type StoredIntent } from "../restricted-live/x402scan-once.js";

const nonce=`0x${"11".repeat(32)}` as const, txHash=`0x${"aa".repeat(32)}`;
const challenge=():LiveChallenge=>({x402Version:2,resource:{url:X402SCAN_ROUTE.url,method:"GET"},accepts:[{scheme:"exact",network:"eip155:8453",amount:"10000",asset:X402SCAN_ROUTE.asset,payTo:X402SCAN_ROUTE.payTo,maxTimeoutSeconds:300,extra:{name:"USD Coin",version:"2"}}]});
const unpaid=(c=challenge())=>new Response("",{status:402,headers:{"payment-required":Buffer.from(JSON.stringify(c)).toString("base64")}});
const paid=(metadata?:Record<string,unknown>)=>new Response('{"buyers":[]}',{status:200,headers:{"content-type":"application/json",...(metadata?{"payment-response":Buffer.from(JSON.stringify(metadata)).toString("base64")}:{})}});
const mutate=(fn:(c:LiveChallenge)=>void)=>{const c=challenge();fn(c);return unpaid(c);};

describe("pinned x402scan one-shot and reconciliation",()=>{
  const dirs:string[]=[];afterEach(()=>{for(const d of dirs.splice(0))fs.rmSync(d,{recursive:true,force:true});});
  const stateFile=()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),"x402-once-"));dirs.push(d);return path.join(d,"state.db");};
  it("migrates legacy intents by adding proposal_id without changing settled rows",()=>{const file=stateFile(),db=new Database(file);db.exec("CREATE TABLE x402_one_shot_intents (idempotency_key TEXT PRIMARY KEY, nonce TEXT UNIQUE NOT NULL, challenge_fingerprint TEXT NOT NULL, status TEXT NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, response_status INTEGER, balance_after TEXT)");db.prepare("INSERT INTO x402_one_shot_intents VALUES (?,?,?,?,?,?,?,?)").run("legacy",`0x${"11".repeat(32)}`,"fp","SETTLED",1,2,200,"4990000");db.close();const state=new OneShotState(file),check=new Database(file,{readonly:true}),columns=(check.prepare("PRAGMA table_info(x402_one_shot_intents)").all() as Array<{name:string}>).map(row=>row.name);expect(columns).toContain("proposal_id");expect(state.get("legacy")).toMatchObject({idempotency_key:"legacy",status:"SETTLED",balance_after:"4990000"});check.close();state.close();});
  const paymentDeps=(responses:Array<Response|Error>,balances:bigint[]):OneShotDependencies&{fetch:ReturnType<typeof vi.fn>;signer:{sign:ReturnType<typeof vi.fn>}}=>{
    const fetchMock=vi.fn(async()=>{const r=responses.shift();if(r instanceof Error)throw r;if(!r)throw new Error("unexpected HTTP call");return r;});
    const signer={sign:vi.fn(async()=>`0x${"22".repeat(65)}` as `0x${string}`)};
    return{fetch:fetchMock as unknown as typeof fetch,getBalanceBaseUnits:vi.fn(async()=>balances.shift()??4_990_000n),signer,confirm:vi.fn(async()=>"PAY 0.01 USDC"),now:()=>1_786_350_000_000,nonce:()=>nonce,stateFile:stateFile(),walletAddress:X402SCAN_WALLET,audit:{record:vi.fn()},sleep:vi.fn(async()=>{}),pollDelaysMs:[0,1]};
  };
  const uncertain=(file:string,overrides:Partial<StoredIntent>={})=>{const s=new OneShotState(file);s.reserve("id",nonce,"fp",1,5_000_000n);s.mark("id","UNCERTAIN",2,200,5_000_000n);s.close();return{...readIntentReadonly(file)!,...overrides};};
  const reconcileDeps=(file:string,balances:bigint[],extra:Partial<OneShotDependencies>={}):OneShotDependencies=>({fetch:vi.fn(async()=>{throw new Error("HTTP forbidden");}) as unknown as typeof fetch,getBalanceBaseUnits:vi.fn(async()=>balances.shift()??balances.at(-1)??5_000_000n),stateFile:file,walletAddress:X402SCAN_WALLET,sleep:vi.fn(async()=>{}),pollDelaysMs:[0,1,2,4,8],...extra});

  it("handles HTTP 200, stale first balance, then exact second balance without retry",async()=>{const d=paymentDeps([unpaid(),paid()],[5_000_000n,5_000_000n,4_990_000n]);await expect(executeX402scanOnceForTest(d)).resolves.toEqual({status:200,balanceAfterBaseUnits:4_990_000n});expect(d.fetch).toHaveBeenCalledTimes(2);expect(d.signer.sign).toHaveBeenCalledTimes(1);expect(readIntentReadonly(d.stateFile!)?.status).toBe("SETTLED");});
  it("persists and uses HTTP 200 settlement transaction metadata",async()=>{const metadata={success:true,transaction:txHash,network:"eip155:8453",payer:X402SCAN_WALLET,recipient:X402SCAN_ROUTE.payTo,amount:"10000"};const d=paymentDeps([unpaid(),paid(metadata)],[5_000_000n,4_990_000n]);d.getReceipt=vi.fn(async()=>({status:"0x1",logs:[]}));await executeX402scanOnceForTest(d);const row=readIntentReadonly(d.stateFile!)!;expect(row.response_status).toBe(200);expect(row.payment_response_header).toBeTruthy();expect(row.settlement_tx_hash).toBe(txHash);expect(row.response_received_at).toBeTruthy();expect(row.resource_response_metadata).toContain("bodySha256");});
  it("supports delayed settlement visibility",async()=>{const f=stateFile(),intent=uncertain(f);const d=reconcileDeps(f,[5_000_000n,5_000_000n,4_990_000n]);const r=await reconcileIntent(d,intent);expect(r.classification).toBe("SETTLED");expect(d.getBalanceBaseUnits).toHaveBeenCalledTimes(3);});
  it("leaves no-settlement evidence uncertain after bounded polling",async()=>{const f=stateFile(),intent=uncertain(f);const d=reconcileDeps(f,[5_000_000n,5_000_000n,5_000_000n,5_000_000n,5_000_000n]);const r=await reconcileIntent(d,intent);expect(r).toMatchObject({classification:"UNCERTAIN",evidence:"settlement not visible within bounded polling window"});});
  it("prevents float precision regressions with exact bigint delta",async()=>{const f=stateFile(),intent=uncertain(f,{pre_balance_base_units:"5000000",payment_amount_base_units:"10000"});expect((await reconcileIntent(reconcileDeps(f,[4_990_000n]),intent)).classification).toBe("SETTLED");expect(JSON.stringify(intent)).not.toContain("4.99");});
  it("keeps wrong lower balance and unexpectedly higher balance uncertain",async()=>{for(const [value,evidence] of [[4_980_000n,"balance changed by wrong amount"],[5_010_000n,"balance unexpectedly higher"]] as const){const f=stateFile(),intent=uncertain(f);await expect(reconcileIntent(reconcileDeps(f,[value]),intent)).resolves.toMatchObject({classification:"UNCERTAIN",evidence});}});
  it("classifies a failed receipt as failed and a mismatched receipt as uncertain",async()=>{const f=stateFile(),base=uncertain(f,{settlement_tx_hash:txHash});await expect(reconcileIntent(reconcileDeps(f,[5_000_000n],{getReceipt:async()=>({status:"0x0",logs:[]})}),base)).resolves.toMatchObject({classification:"FAILED"});await expect(reconcileIntent(reconcileDeps(f,[5_000_000n],{getReceipt:async()=>({status:"0x1",logs:[{address:X402SCAN_ROUTE.asset,topics:["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",`0x${"0".repeat(24)}${X402SCAN_WALLET.slice(2)}`,`0x${"0".repeat(24)}${"00".repeat(20)}`],data:"0x2710"}]})}),base)).resolves.toMatchObject({classification:"UNCERTAIN",evidence:"settlement receipt mismatch"});});
  it("rejects PAYMENT-RESPONSE recipient and amount mismatches",()=>{const encode=(x:unknown)=>Buffer.from(JSON.stringify(x)).toString("base64");expect(()=>decodePaymentResponse(encode({recipient:"0x0000000000000000000000000000000000000001",amount:"10000"}))).toThrow("recipient mismatch");expect(()=>decodePaymentResponse(encode({recipient:X402SCAN_ROUTE.payTo,amount:"10001"}))).toThrow("amount mismatch");});
  it("recovers after restart, transitions atomically, and repeated reconciliation is idempotent",async()=>{const f=stateFile();uncertain(f);const d=reconcileDeps(f,[4_990_000n]);await expect(runX402scanReconciliation(d)).resolves.toMatchObject({classification:"SETTLED",transitioned:true});const immutable={...readIntentReadonly(f)!};await expect(runX402scanReconciliation(reconcileDeps(f,[]))).resolves.toMatchObject({classification:"SETTLED",transitioned:false});const after=readIntentReadonly(f)!;expect(after.status).toBe("SETTLED");expect(after.nonce).toBe(immutable.nonce);expect(after.idempotency_key).toBe(immutable.idempotency_key);expect(after.challenge_fingerprint).toBe(immutable.challenge_fingerprint);});
  it("SETTLED cannot transition backwards",()=>{const f=stateFile();uncertain(f);const s=new OneShotState(f);s.settleUncertain("id",3,4_990_000n);expect(()=>s.mark("id","UNCERTAIN",4)).toThrow("terminal");s.close();expect(readIntentReadonly(f)?.status).toBe("SETTLED");});
  it("reconciliation cannot fetch, sign, resubmit, or create a nonce",async()=>{const f=stateFile();uncertain(f);const fetchMock=vi.fn(),sign=vi.fn(),nonceFn=vi.fn();const d=reconcileDeps(f,[4_990_000n],{fetch:fetchMock as unknown as typeof fetch,signer:{sign},nonce:nonceFn});await runX402scanReconciliation(d);expect(fetchMock).not.toHaveBeenCalled();expect(sign).not.toHaveBeenCalled();expect(nonceFn).not.toHaveBeenCalled();});
  it.each([["recipient",(c:LiveChallenge)=>{c.accepts[0].payTo="0x0000000000000000000000000000000000000001"}],["amount",(c:LiveChallenge)=>{c.accepts[0].amount="10001"}],["token",(c:LiveChallenge)=>{c.accepts[0].asset="0x0000000000000000000000000000000000000001"}],["chain",(c:LiveChallenge)=>{c.accepts[0].network="eip155:1"}],["scheme",(c:LiveChallenge)=>{c.accepts[0].scheme="permit"}],["version",(c:LiveChallenge)=>{c.x402Version=1}],["url",(c:LiveChallenge)=>{c.resource.url+="/x"}],["method",(c:LiveChallenge)=>{c.resource.method="POST"}]])("rejects changed challenge %s",async(_n,fn)=>{await expect(decodeAndValidateChallenge(mutate(fn))).rejects.toMatchObject({code:"CHALLENGE_MISMATCH"});});
  it("rejects redirect and arbitrary calldata",async()=>{const r=unpaid();Object.defineProperty(r,"redirected",{value:true});await expect(decodeAndValidateChallenge(r)).rejects.toMatchObject({code:"REDIRECT_DENIED"});await expect(decodeAndValidateChallenge(mutate(c=>{c.accepts[0].calldata="0xdead";}))).rejects.toMatchObject({code:"CHALLENGE_MISMATCH"});});
  it("crash states and uncertain submissions remain permanently blocked",async()=>{for(const status of ["RESERVED","SIGNED","SUBMITTED","UNCERTAIN"] as const){const f=stateFile(),s=new OneShotState(f);s.reserve("id",nonce,"fp",1,5_000_000n);if(status!=="RESERVED")s.mark("id",status,2);s.close();const restarted=new OneShotState(f);expect(()=>restarted.reserve("new",`0x${"44".repeat(32)}`,"fp",3,5_000_000n)).toThrow(`Prior payment intent is ${status}`);restarted.close();}});
  it("marks timeout after submission uncertain and never retries",async()=>{const d=paymentDeps([unpaid(),new Error("timeout")],[5_000_000n]);await expect(executeX402scanOnceForTest(d)).rejects.toMatchObject({code:"SETTLEMENT_UNCERTAIN"});expect(d.fetch).toHaveBeenCalledTimes(2);expect(readIntentReadonly(d.stateFile!)?.status).toBe("UNCERTAIN");});
  it("requires exact confirmation and enforces reserve/funding ceiling",async()=>{const no=paymentDeps([unpaid()],[5_000_000n]);no.confirm=vi.fn(async()=>"yes");await expect(executeX402scanOnceForTest(no)).rejects.toMatchObject({code:"CONFIRMATION_DENIED"});for(const balance of [4_000_000n,5_000_001n]){const d=paymentDeps([unpaid()],[balance]);await expect(executeX402scanOnceForTest(d)).rejects.toMatchObject({code:"BALANCE_DENIED"});expect(d.signer.sign).not.toHaveBeenCalled();}});
  it("denies stale and general signing surfaces",async()=>{const signer=new PinnedEip3009Signer();expect(()=>signer.signTransaction()).toThrow("disabled");expect(()=>signer.personalSign()).toThrow("disabled");expect(()=>signer.ethSign()).toThrow("disabled");await expect(signer.sign({from:X402SCAN_WALLET,to:X402SCAN_ROUTE.payTo,value:"10000",validAfter:"0",validBefore:"1",nonce})).rejects.toMatchObject({code:"SIGNING_DENIED"});});
  it("redacts secret-shaped audit metadata",async()=>{const d=path.dirname(stateFile()),file=path.join(d,"audit.jsonl"),{RestrictedLiveAudit}=await import("../restricted-live/audit.js");new RestrictedLiveAudit(file).record("failure",{privateKey:"sentinel",signature:"sentinel",authorization:"sentinel"});const text=fs.readFileSync(file,"utf8");expect(text).not.toContain("sentinel");expect(text).toContain("[REDACTED]");});
  it("validates successful receipt without logs",()=>{expect(validateReceipt({status:"0x1",blockNumber:"0x1",logs:[]})).toBe("SETTLED");});
});
