import fs from "node:fs";
import path from "node:path";
import readline from "node:readline/promises";
import { randomUUID } from "node:crypto";
import Database from "better-sqlite3";
import { LIVE_DRY_RUN, LIVE_PATHS, RESTRICTED_LIVE_MODE, RestrictedLiveViolation, initializeLiveRoot } from "./mode.js";
import { X402SCAN_ROUTE, createLiveDependencies, createLivePreviewDependencies, decodeAndValidateChallenge, executeX402scanOnceForTest, formatPaymentPreview, type OneShotDependencies } from "./x402scan-once.js";

export interface PaymentProposal {
  proposalId:string; createdAt:string; rationale:string; resourceUrl:string; method:string;
  expectedPriceBaseUnits:string; expectedRecipient:string; expectedChainId:number; expectedToken:string;
  expectedScheme:string; maxTimeoutSeconds:number;
}
export type ProposalState="PROPOSED"|"APPROVED"|"EXECUTING"|"SETTLED"|"UNCERTAIN"|"REJECTED"|"EXPIRED";
interface StoredProposal extends PaymentProposal { state:ProposalState; expiresAt:number; balanceBaseUnits:string; hourlySpendBaseUnits:string; dailySpendBaseUnits:string; updatedAt:number }
export interface ProposalDependencies { getBalanceBaseUnits:()=>Promise<bigint>; now?:()=>number; proposalFile?:string; intentFile?:string; id?:()=>string }
const TTL_MS=10*60*1000;
function fail(code:string,message:string):never{throw new RestrictedLiveViolation(code,message);}
function proposalFile(d?:ProposalDependencies){return d?.proposalFile??path.join(LIVE_PATHS.state,"payment-proposals.db");}
function intentFile(d?:ProposalDependencies){return d?.intentFile??path.join(LIVE_PATHS.state,"x402-one-shot.db");}

export class ProposalStore {
  private db:Database.Database;
  constructor(file:string){fs.mkdirSync(path.dirname(file),{recursive:true,mode:0o700});this.db=new Database(file);fs.chmodSync(file,0o600);this.db.pragma("journal_mode = WAL");this.db.exec("CREATE TABLE IF NOT EXISTS payment_proposals (proposal_id TEXT PRIMARY KEY, created_at TEXT NOT NULL, rationale TEXT NOT NULL, resource_url TEXT NOT NULL, method TEXT NOT NULL, expected_price_base_units TEXT NOT NULL, expected_recipient TEXT NOT NULL, expected_chain_id INTEGER NOT NULL, expected_token TEXT NOT NULL, expected_scheme TEXT NOT NULL, max_timeout_seconds INTEGER NOT NULL, state TEXT NOT NULL, expires_at INTEGER NOT NULL, balance_base_units TEXT NOT NULL, hourly_spend_base_units TEXT NOT NULL, daily_spend_base_units TEXT NOT NULL, updated_at INTEGER NOT NULL)");}
  close(){this.db.close();}
  insert(p:StoredProposal){this.db.prepare("INSERT INTO payment_proposals VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(p.proposalId,p.createdAt,p.rationale,p.resourceUrl,p.method,p.expectedPriceBaseUnits,p.expectedRecipient,p.expectedChainId,p.expectedToken,p.expectedScheme,p.maxTimeoutSeconds,p.state,p.expiresAt,p.balanceBaseUnits,p.hourlySpendBaseUnits,p.dailySpendBaseUnits,p.updatedAt);}
  get(id:string,now=Date.now()):StoredProposal|undefined{this.db.prepare("UPDATE payment_proposals SET state='EXPIRED',updated_at=? WHERE proposal_id=? AND state='PROPOSED' AND expires_at<?").run(now,id,now);const r=this.db.prepare("SELECT * FROM payment_proposals WHERE proposal_id=?").get(id) as Record<string,unknown>|undefined;if(!r)return;return{proposalId:String(r.proposal_id),createdAt:String(r.created_at),rationale:String(r.rationale),resourceUrl:String(r.resource_url),method:String(r.method),expectedPriceBaseUnits:String(r.expected_price_base_units),expectedRecipient:String(r.expected_recipient),expectedChainId:Number(r.expected_chain_id),expectedToken:String(r.expected_token),expectedScheme:String(r.expected_scheme),maxTimeoutSeconds:Number(r.max_timeout_seconds),state:String(r.state) as ProposalState,expiresAt:Number(r.expires_at),balanceBaseUnits:String(r.balance_base_units),hourlySpendBaseUnits:String(r.hourly_spend_base_units),dailySpendBaseUnits:String(r.daily_spend_base_units),updatedAt:Number(r.updated_at)};}
  transition(id:string,from:ProposalState,to:ProposalState,now:number){const result=this.db.prepare("UPDATE payment_proposals SET state=?,updated_at=? WHERE proposal_id=? AND state=?").run(to,now,id,from);if(result.changes!==1)fail("PROPOSAL_STATE_DENIED",`Cannot transition proposal ${from} -> ${to}`);}
}

function spendSince(file:string,cutoff:number):bigint{if(!fs.existsSync(file))return 0n;const db=new Database(file,{readonly:true,fileMustExist:true});try{const rows=db.prepare("SELECT payment_amount_base_units FROM x402_one_shot_intents WHERE status='SETTLED' AND COALESCE(settled_at,updated_at)>=?").all(cutoff) as Array<{payment_amount_base_units:string|null}>;return rows.reduce((s,r)=>s+BigInt(r.payment_amount_base_units??"10000"),0n);}finally{db.close();}}
function validatePinned(p:PaymentProposal){if(p.resourceUrl!==X402SCAN_ROUTE.url||p.method!=="GET"||p.expectedPriceBaseUnits!=="10000"||p.expectedRecipient.toLowerCase()!==X402SCAN_ROUTE.payTo.toLowerCase()||p.expectedChainId!==8453||p.expectedToken.toLowerCase()!==X402SCAN_ROUTE.asset.toLowerCase()||p.expectedScheme!=="exact"||p.maxTimeoutSeconds!==300)fail("PROPOSAL_TAMPERED","Proposal differs from pinned route");}

export async function createPaymentProposal(rationale:string,deps:ProposalDependencies):Promise<string>{if(!RESTRICTED_LIVE_MODE)fail("MODE_REQUIRED","Restricted-live proposal mode required");if(typeof rationale!=="string"||rationale.trim().length<3||rationale.length>500)fail("PROPOSAL_INVALID","Rationale must be 3..500 characters");initializeLiveRoot();const now=deps.now?.()??Date.now(),balance=await deps.getBalanceBaseUnits(),hourly=spendSince(intentFile(deps),now-3_600_000),daily=spendSince(intentFile(deps),now-86_400_000);if(balance>5_000_000n||balance-10_000n<4_000_000n||hourly+10_000n>250_000n||daily+10_000n>500_000n)fail("BUDGET_DENIED","Proposal exceeds balance, reserve, or spend budget");const proposalId=deps.id?.()??randomUUID(),p:StoredProposal={proposalId,createdAt:new Date(now).toISOString(),rationale:rationale.trim(),resourceUrl:X402SCAN_ROUTE.url,method:"GET",expectedPriceBaseUnits:"10000",expectedRecipient:X402SCAN_ROUTE.payTo,expectedChainId:8453,expectedToken:X402SCAN_ROUTE.asset,expectedScheme:"exact",maxTimeoutSeconds:300,state:"PROPOSED",expiresAt:now+TTL_MS,balanceBaseUnits:balance.toString(),hourlySpendBaseUnits:hourly.toString(),dailySpendBaseUnits:daily.toString(),updatedAt:now};const store=new ProposalStore(proposalFile(deps));try{store.insert(p);}finally{store.close();}return proposalId;}

export interface ReviewDependencies extends ProposalDependencies { fetch:typeof fetch; executionDeps:OneShotDependencies; confirm?:(preview:string,proposalId:string)=>Promise<string> }
export async function reviewAndExecuteProposal(id:string,deps:ReviewDependencies){if(!RESTRICTED_LIVE_MODE||LIVE_DRY_RUN)fail("MODE_REQUIRED","Payment review execution requires restricted-live mode with dry-run disabled");const now=deps.now?.()??Date.now(),store=new ProposalStore(proposalFile(deps));let p:StoredProposal;try{const found=store.get(id,now);if(!found)fail("PROPOSAL_NOT_FOUND","Proposal not found");p=found;validatePinned(p);if(p.state==="EXPIRED")fail("PROPOSAL_EXPIRED","Proposal expired");if(p.state!=="PROPOSED")fail("PROPOSAL_STATE_DENIED",`Proposal is ${p.state}`);if(now>p.expiresAt){store.transition(id,"PROPOSED","EXPIRED",now);fail("PROPOSAL_EXPIRED","Proposal expired");}const response=await deps.fetch(X402SCAN_ROUTE.url,{method:"GET",headers:{accept:"application/json"},redirect:"manual",signal:AbortSignal.timeout(30_000)});await decodeAndValidateChallenge(response);const balance=await deps.getBalanceBaseUnits(),hourly=spendSince(intentFile(deps),now-3_600_000),daily=spendSince(intentFile(deps),now-86_400_000);if(balance>5_000_000n||balance-10_000n<4_000_000n||hourly+10_000n>250_000n||daily+10_000n>500_000n)fail("BUDGET_DENIED","Review exceeds balance, reserve, or spend budget");const preview=`Proposal rationale: ${p.rationale}\n${formatPaymentPreview(balance,hourly,daily,Math.floor(now/1000)+300)}\nRemaining reserve after: ${String(balance-10_000n-4_000_000n)} base units`;const answer=await(deps.confirm??terminalReview)(preview,id);if(answer!==`APPROVE PAYMENT ${id}`){store.transition(id,"PROPOSED","REJECTED",now);fail("CONFIRMATION_DENIED","Exact proposal approval not received");}store.transition(id,"PROPOSED","APPROVED",now);store.transition(id,"APPROVED","EXECUTING",now);}finally{store.close();}
  try{const result=await executeX402scanOnceForTest({...deps.executionDeps,proposalId:id,confirm:async()=>"PAY 0.01 USDC"});const s=new ProposalStore(proposalFile(deps));try{s.transition(id,"EXECUTING","SETTLED",deps.now?.()??Date.now());}finally{s.close();}return result;}catch(e){const s=new ProposalStore(proposalFile(deps));try{const current=s.get(id);if(current?.state==="EXECUTING")s.transition(id,"EXECUTING","UNCERTAIN",deps.now?.()??Date.now());}finally{s.close();}throw e;}}

async function terminalReview(preview:string,id:string){process.stdout.write(`${preview}\n\nType exactly: APPROVE PAYMENT ${id}\n> `);const rl=readline.createInterface({input:process.stdin,output:process.stdout});try{return await rl.question("");}finally{rl.close();}}
export function createLiveProposalDependencies():ProposalDependencies{const d=createLivePreviewDependencies();return{getBalanceBaseUnits:d.getBalanceBaseUnits};}
export function createLiveReviewDependencies():ReviewDependencies{const read=createLivePreviewDependencies();return{getBalanceBaseUnits:read.getBalanceBaseUnits,fetch,executionDeps:createLiveDependencies()};}
